apiVersion: v1
kind: Service
metadata:
  name: updatedhealthproject-service
spec:
  type: NodePort
  selector:
    app: updatedhealthproject
  ports:
  - protocol: TCP
    port: 80  # Port that the service will expose
    targetPort: 8082  # Port that the container listens on
    nodePort: 30000  # NodePort range is 30000-32767
